name: k1-uboot

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

env:
  ARCH: riscv
  CROSS_COMPILE: riscv64-linux-gnu-

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Install software
        run: |
              sudo apt update && \
              sudo apt install -y gdisk dosfstools g++-riscv64-linux-gnu cpp-riscv64-linux-gnu build-essential \
                                  libncurses-dev gawk flex bison openssl libssl-dev tree u-boot-tools \
                                  dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf device-tree-compiler

      - name: Checkout uboot
        uses: actions/checkout@v4

      - name: uboot compile
        run: |
              mkdir output
              ${CROSS_COMPILE}gcc -v

              pushd $PWD
                make k1_defconfig
                make -j`nproc`

                # factory
                mkdir -p ${GITHUB_WORKSPACE}/output/factory
                cp -v u-boot.itb ${GITHUB_WORKSPACE}/output/
                cp -v u-boot-env-default.bin ${GITHUB_WORKSPACE}/output/env.bin
                cp -v bootinfo_*.bin ${GITHUB_WORKSPACE}/output/factory
                cp -v FSBL.bin ${GITHUB_WORKSPACE}/output/factory
              popd
              tree ${GITHUB_WORKSPACE}/output

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: k1-uboot
          path: output/*
          retention-days: 30
